[[customizations.user]]
name = "centos"
password = "centos"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/"
minsize = "16 GiB"

[[customizations.filesystem]]
mountpoint = "/boot"
size = "1 GiB"