[[customizations.user]]
name = "centos"
password = "centos"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/"
minsize = "6 GiB"

[[customizations.filesystem]]
mountpoint = "/boot"
minsize = "1 GiB"