[[customizations.user]]
name = "fedora"
password = "fedora"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/"
minsize = "6 GiB"

[[customizations.filesystem]]
mountpoint = "/boot"
minsize = "2 GiB"