[[customizations.user]]
name = "fedora"
password = "fedora"
groups = ["wheel"]

[[customizations.filesystem]]
mountpoint = "/"
minsize = "16 GiB"

[[customizations.filesystem]]
mountpoint = "/boot"
size = "2 GiB"
